Product page
NoValentina/fake-burrberry-frontend pull request #4
Opened 2017-07-31 21:05 UTC by NoValentina

2017-08-01 09:16 UTC, evgenyrodionov commented
> Мы вешаем ревью только после того как считаете что работу сделали идеально

на будущее
https://rawgit.com/NoValentina/fake-burrberry-frontend/product-page/index.html

2017-08-01 17:49 UTC, evgenyrodionov commented
Если открыть с айфона, то будет как ниже.
1) не фиксируй ширину специально
2) ты пользуешься девтулз? Если нет, в телеграфе я писал про это
3) чтобы исправить проблему, тебе нужно прописать в head специальный мета-тег, который укажет что ширина верстки равна ширине девайса. Гугли meta viewport

![image](https://user-images.githubusercontent.com/775692/28838966-b9169964-76fa-11e7-8994-90bfd0fb1cdd.png)

2017-08-01 17:53 UTC, evgenyrodionov commented
Логотип не загрузился

![image](https://user-images.githubusercontent.com/775692/28839077-20defbc2-76fb-11e7-890a-e0f6476fb797.png)
![image](https://user-images.githubusercontent.com/775692/28839100-37f8f510-76fb-11e7-97ca-53c03939ff90.png)
![image](https://user-images.githubusercontent.com/775692/28839109-41d47212-76fb-11e7-94d5-61adbe28ed28.png)
![image](https://user-images.githubusercontent.com/775692/28839131-52f97290-76fb-11e7-84df-460d31c845cf.png)
![image](https://user-images.githubusercontent.com/775692/28839143-5b76a474-76fb-11e7-858f-227e5754466b.png)
![image](https://user-images.githubusercontent.com/775692/28839149-636e3a70-76fb-11e7-977a-41f45145b46e.png)

2017-08-01 17:53 UTC, imevro requested changes
фикси дизайн

2017-08-01 17:53 UTC, evgenyrodionov commented
И удали дс_стор из файла через git rm .DS_Store

2017-08-02 10:03 UTC, evgenyrodionov commented
Валя, верни логотип Бёрберри!

2017-08-02 10:05 UTC, evgenyrodionov commented
Поиграйся с лайн-хейт и разберись с бордером — он не совпадает к макету
![image](https://user-images.githubusercontent.com/775692/28868723-fa40ada2-7782-11e7-9b0f-e18bd9a1b2e7.png)

![image](https://user-images.githubusercontent.com/775692/28868738-07e421a0-7783-11e7-8482-262945ac818c.png)
![image](https://user-images.githubusercontent.com/775692/28868748-0fd602fc-7783-11e7-900c-dbc5dcd5b9d8.png)
![image](https://user-images.githubusercontent.com/775692/28868766-19168288-7783-11e7-9fd7-c81981f5c8b2.png)
![image](https://user-images.githubusercontent.com/775692/28868781-261e0988-7783-11e7-877b-1d72e3df6f69.png)

2017-08-02 10:06 UTC, imevro requested changes
↑
+ удали .DS_Store говорил же

2017-08-02 10:06 UTC, evgenyrodionov commented on .gitignore
> +*.DS_Store
Не так, потому что `.DS_Store` это название файла, а не расширение. Поэтому убери звездочку

2017-08-02 17:50 UTC, evgenyrodionov commented
Поправь чутка лайн-хейт в футере
![image](https://user-images.githubusercontent.com/775692/28887017-3c8288ac-77c4-11e7-8f45-5de23dfb8d04.png)

2017-08-02 17:50 UTC, evgenyrodionov commented
Код проверю в полночь, потому что проверку повесила после 8

2017-08-02 17:51 UTC, evgenyrodionov commented
Могу сразу сказать что нейминг плохой, посмотри в сторону http://bem.info

2017-08-02 20:41 UTC, NoValentina commented
<img width="336" alt="screen shot 2017-08-02 at 23 40 21" src="https://user-images.githubusercontent.com/30528287/28894022-2592624e-77dc-11e7-81d4-84a4d00f85d0.png">

2017-08-02 20:42 UTC, NoValentina commented
нейминг поправила

2017-08-02 22:33 UTC, imevro requested changes
удали дссторы, сама посмотри в файлах, они у тебя остались 
https://github.com/NoValentina/fake-burrberry-frontend/pull/4/files

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +    <link rel="stylesheet" href="styles/normalize.css">
подключай через сдн

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +          <img width="300" height="400" src="images/slide1.jpg" alt="Slide 1">
лучше через цсс указывать ширину и высоту

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +        <button class="btn-color-dark"></button>
.product-color + .product-btn-color > .btn-color-dark?

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +        <button class="btn-action-select">SELECT A SIZE</button>
откуда 4 отступа

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +        <button class="btn-color-dark"></button>
нет типа, нет контента внутри замещающего (нужен для скринридеров)

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +      <img class="product-dropdown-open" src="images/Triangle.svg">
через цсс

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +         Invented by Thomas Burberry in 1879,<br> cotton gabardine is a tightly woven and<br> breathable fabric that protects against wind <br> and rain.<br>
это параграфы + можешь не расставлять руками бры внутри предложения

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +        <li class="dropdown-list-item">Сoat length: 98cm/38.6in. This is based on a size UK 48 as proportions change slightly according to size.</li>
с сервера будет описание приходить без классов

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +      <div class="recommendations-product-descriprion">
descriprion → description

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +      <div class="recommendations-product-descriprion">
почему не ссылкой

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +          <img class="recommendations-product-photo" src="https://assets.burberry.com/is/image/Burberryltd/f51a470fc157e3014a115c64276c2e124d9fc477.jpg?$BBY_V2_ML_3X4$&hei=260&wid=195">
поч 4 пробела отступ, будь внимательнее

2017-08-02 22:33 UTC, evgenyrodionov commented on index.html
> +    <div class="footer-information-">
footer-information-?

2017-08-02 22:33 UTC, evgenyrodionov commented on styles/style.css
> +  margin: 0;
плохо обнулять для всех

2017-08-02 22:34 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28897959-e452b9e0-77eb-11e7-854f-84d83564e82e.png)
![image](https://user-images.githubusercontent.com/775692/28897963-ec811c56-77eb-11e7-80f0-e1d07a4f72af.png)

2017-08-03 09:32 UTC, NoValentina commented
h { } cтавлю потому что иначе normalize.css задает свои значения

2017-08-03 11:06 UTC, NoValentina commented
<img width="315" alt="screen shot 2017-08-03 at 14 04 31" src="https://user-images.githubusercontent.com/30528287/28919133-ce2f545c-7854-11e7-9c3d-cebd94d35648.png">
<img width="832" alt="screen shot 2017-08-03 at 14 04 14" src="https://user-images.githubusercontent.com/30528287/28919143-dee67a00-7854-11e7-895d-df763fdbbf8d.png">
так можно?

2017-08-03 12:12 UTC, NoValentina commented
<img width="715" alt="screen shot 2017-08-03 at 15 11 45" src="https://user-images.githubusercontent.com/30528287/28921325-26c7525a-785e-11e7-87e5-25809710a1e5.png">
тег а использовать?

2017-08-03 12:22 UTC, evgenyrodionov commented
После 12 — след проверка

2017-08-03 12:23 UTC, evgenyrodionov commented
Вопросы лучше в чат спрашивать, чё тянуть

2017-08-03 18:42 UTC, imevro reviewed
почисти код, прогони каким-нибудь бьютифаером, он сейчас какой-то неаккуратно некрасивый

2017-08-03 18:42 UTC, evgenyrodionov commented on index.html
> +        <button class="btn-dark" type="button" title="Color: black"></button>
почему ты не хочешь разместить контент внутри тегов?

2017-08-03 18:42 UTC, evgenyrodionov commented on index.html
> +      <div class="product-description-btn">
кнопка одна или их несколько?

2017-08-03 18:42 UTC, evgenyrodionov commented on index.html
> +      <div class="product-dropdown-open"></div>
в цсс через :after

2017-08-03 18:42 UTC, evgenyrodionov commented on index.html
> +       <ul>
юл идёт в том же блоке с дескрипшеном

2017-08-03 20:50 UTC, NoValentina commented on index.html
> +      <div class="product-dropdown-open"></div>
+

2017-08-03 20:50 UTC, NoValentina commented on index.html
> +       <ul>
+

2017-08-03 21:05 UTC, NoValentina commented on index.html
> +        <button class="btn-dark" type="button" title="Color: black"></button>
+

2017-08-03 21:10 UTC, NoValentina commented on index.html
> +      <div class="product-description-btn">
+

2017-08-04 09:10 UTC, imevro requested changes
- a11y
- большая вложенность в галерее, в описании
- кнопок нет на дропдаунах — как их открывать?
- спрос глобальных стилей

2017-08-04 09:10 UTC, evgenyrodionov commented on index.html
> +        <button class="btn-dark" type="button">Color: black</button>
Colour или Color?

2017-08-04 19:33 UTC, NoValentina commented on index.html
> +        <button class="btn-dark" type="button">Color: black</button>
+

2017-08-08 10:50 UTC, merged