Product page tablet
NoValentina/fake-burrberry-frontend pull request #5
Opened 2017-08-04 21:02 UTC by NoValentina

2017-08-04 21:03 UTC, NoValentina commented
Замечания твои еще не все успела поправить. Делала планшет. Но обязательно переделаю

2017-08-04 21:21 UTC, evgenyrodionov commented
Направляй ПР в ту ветку от которой бранчевалась

2017-08-04 21:22 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28987497-20b7ebb0-7974-11e7-9e36-a1e6a157dbae.png)

2017-08-04 21:22 UTC, evgenyrodionov commented
Шрифты в футере

![image](https://user-images.githubusercontent.com/775692/28987506-29696e0a-7974-11e7-8254-d59f53af843b.png)

2017-08-04 21:23 UTC, evgenyrodionov commented
Дыра между пикчами 
![image](https://user-images.githubusercontent.com/775692/28987520-353efa56-7974-11e7-9e45-a82547deef3e.png)

2017-08-05 15:23 UTC, NoValentina commented
Все поправила, что ты просил. Почистила код и протестировала.

2017-08-05 17:55 UTC, imevro requested changes

2017-08-05 17:55 UTC, evgenyrodionov commented on index.html
> +              <button class="btn-dark" type="button">Colour: black</button>
кнопки лучше именовать по действию, кстати

2017-08-05 17:55 UTC, evgenyrodionov commented on index.html
> +              <button class="btn-dark" type="button">Colour: black</button>
Change colour to black

2017-08-05 17:55 UTC, evgenyrodionov commented on index.html
> +          <a class="recommendations-product-description col-xs-6 col-md-3" href="index.html">
не смешивай свои классы и классы сетки

2017-08-05 17:55 UTC, evgenyrodionov commented on index.html
> +          <a class="recommendations-link" href="#">WE RECOMMEND</a>
а почему ссылка?

2017-08-05 17:55 UTC, evgenyrodionov commented on index.html
> +            <ul>
юл-ли это только для списков внутри текста, не для разметки

2017-08-05 19:46 UTC, NoValentina commented on index.html
> +              <button class="btn-dark" type="button">Colour: black</button>
+

2017-08-05 19:50 UTC, NoValentina commented on index.html
> +          <a class="recommendations-link" href="#">WE RECOMMEND</a>
+

2017-08-05 19:55 UTC, NoValentina commented on index.html
> +          <a class="recommendations-product-description col-xs-6 col-md-3" href="index.html">
+

2017-08-05 20:21 UTC, NoValentina commented on index.html
> +            <ul>
+

2017-08-05 20:24 UTC, NoValentina commented
Все пофиксила!

2017-08-05 21:24 UTC, imevro requested changes

2017-08-05 21:24 UTC, evgenyrodionov commented on styles/style.css
> +.btn-change-colour-to-black,
Достаточно `.btn-change-colour`, классов-то у элементов может быть несколько

2017-08-06 08:34 UTC, merged

2017-08-06 08:37 UTC, evgenyrodionov commented
Гит чекаут мастер, гит пулл ориджин мастер --ребейз, новые бранчи от нового мастера создавай