feat: header and footer components
NoValentina/fake-burrberry-frontend pull request #6
Opened 2017-08-08 20:44 UTC by NoValentina

2017-08-11 18:02 UTC, imevro requested changes

2017-08-11 18:02 UTC, evgenyrodionov commented on public/manifest.json
> +  "name": "Create Burberry App",
НЕ ПОНЯЛ

2017-08-11 18:02 UTC, evgenyrodionov commented on src/DropDown/index.js
> +  const Button = styled.button`
вынеси за пределы рендера

2017-08-11 18:02 UTC, evgenyrodionov commented on src/DropDown/index.js
> +const DropDown = (props) => {
это не дропдаун

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Footer/Navigation/index.js
> +const FooterMenu = styled.div `
поставь преттир

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Footer/Navigation/index.js
> +import React, { Component } from 'react';
нет нужды создавать директорию ради одного файла index.js, можно спокойно делать Navigation.js

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Footer/Navigation/index.js
> +  const Linkabbr = styled.a`
ссылку в ссылку нельзя

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Header/index.js
> +const Head = styled.header `{
а что за {}?

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Product/Cards/Card/index.js
> +class Card extends Component {
тут не нужен класс

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Product/Cards/index.js
> +    price: '27 000'
цену числом храни, не строкой

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Product/Cards/index.js
> +const RecommendCards = [
просто cards и с маленькой буквы

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Product/Delivery/index.js
> +                  <Name>Free Next Day Delivery</Name>
Label скорее

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Product/Delivery/index.js
> +                  <Rubric>Order before 7pm Monday to Thursday for delivery the next day</Rubric>
описание

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Product/Intro/Color/index.js
> +		border-radius: 6.25rem;
тут вообще табы поползли

2017-08-11 18:02 UTC, evgenyrodionov commented on src/Product/Intro/Properties/index.js
> +        <ListProperties>
что значит листпропертиес?

2017-08-11 18:07 UTC, NoValentina commented on public/manifest.json
> +  "name": "Create Burberry App",
+

2017-08-11 18:11 UTC, NoValentina commented on src/Footer/Navigation/index.js
> +const FooterMenu = styled.div `
Я специально его не ставлю пока, потому что хочу сама научится следить за этим

2017-08-11 18:13 UTC, NoValentina commented on src/Product/Cards/Card/index.js
> +class Card extends Component {
+

2017-08-11 18:13 UTC, NoValentina commented on src/Product/Cards/index.js
> +const RecommendCards = [
+

2017-08-11 18:19 UTC, NoValentina commented on src/Header/index.js
> +const Head = styled.header `{
+

2017-08-11 18:24 UTC, NoValentina commented on src/Footer/Navigation/index.js
> +import React, { Component } from 'react';
+

2017-08-11 18:28 UTC, NoValentina commented on src/Product/Intro/Color/index.js
> +		border-radius: 6.25rem;
+

2017-08-11 18:30 UTC, NoValentina commented on src/Product/Cards/index.js
> +    price: '27 000'
+

2017-08-11 18:36 UTC, NoValentina commented on src/DropDown/index.js
> +  const Button = styled.button`
+

2017-08-11 18:54 UTC, NoValentina commented on src/Product/Intro/Properties/index.js
> +        <ListProperties>
+

2017-08-11 19:01 UTC, NoValentina commented on src/Product/Delivery/index.js
> +                  <Name>Free Next Day Delivery</Name>
+

2017-08-11 19:02 UTC, NoValentina commented on src/Product/Delivery/index.js
> +                  <Rubric>Order before 7pm Monday to Thursday for delivery the next day</Rubric>
+

2017-08-11 19:03 UTC, NoValentina commented on src/Footer/Navigation/index.js
> +  const Linkabbr = styled.a`
+

2017-08-11 19:13 UTC, NoValentina commented on src/Footer/Navigation/index.js
> +const FooterMenu = styled.div `
Поправила везде

2017-08-11 19:20 UTC, NoValentina commented on src/DropDown/index.js
> +const DropDown = (props) => {
+

2017-08-11 19:27 UTC, imevro requested changes

2017-08-11 19:27 UTC, evgenyrodionov commented on src/Product/Cards/index.js
> +const cards = [{
products лучше

2017-08-11 19:27 UTC, evgenyrodionov commented on src/Product/Intro/Slider/index.js
> +      <SliderImg alt="одежда" src={slide2} />
зачем столько префиксов слайдер

2017-08-11 19:28 UTC, NoValentina commented on src/Product/Cards/index.js
> +const cards = [{
+

2017-08-11 19:30 UTC, NoValentina commented on src/Product/Intro/Slider/index.js
> +      <SliderImg alt="одежда" src={slide2} />
+

2017-08-11 23:19 UTC, imevro requested changes

2017-08-11 23:19 UTC, evgenyrodionov commented on src/Product/Cards/index.js
> +            photo={ product.photo }
преттир поставь говорю

2017-08-13 12:19 UTC, ExpFront commented on src/Product/Cards/index.js
> +            photo={ product.photo }
+

2017-08-13 12:58 UTC, merged