Product page react desktop
NoValentina/fake-burrberry-frontend pull request #7
Opened 2017-08-12 17:26 UTC by NoValentina

2017-08-12 21:23 UTC, imevro requested changes

2017-08-12 21:23 UTC, evgenyrodionov commented on src/Header/index.js
> +    width: 221px;
а зачем ширину задавать

2017-08-12 21:23 UTC, evgenyrodionov commented on src/Product/Description/Text/index.js
> +/*const Title = styled.h2`
мусор нужно выносить

2017-08-12 21:23 UTC, evgenyrodionov commented on src/Product/Description/Text/index.js
> +  <div>
див можно выкинуть

2017-08-12 21:23 UTC, evgenyrodionov commented on src/Product/Description/Text/index.js
> +  <div>
а раз див можно выкинуть, то экспортить можно сразу ск, а не создавать реакт-компонент как прокладку

2017-08-12 21:23 UTC, evgenyrodionov commented on src/Product/Description/index.js
> +const Photo2 = styled.img`
nth-child

2017-08-12 21:23 UTC, evgenyrodionov commented on src/Product/Desktop/LinkHelp/index.js
> +const LinkHelp = () =>
прокладки не нужны

2017-08-12 21:23 UTC, evgenyrodionov commented on src/Product/Desktop/Size/index.js
> +    <Buttons sizes={sizes} selectedSize="XL" />
лучше храни индекс выбранного элемента массива

2017-08-12 21:23 UTC, evgenyrodionov commented on src/Product/Intro/Actions/index.js
> +    <Button dark={props.dark} desktop={props.desktop} type="button">
dark? primary

2017-08-12 21:23 UTC, evgenyrodionov commented on src/Product/Intro/Actions/index.js
> +    <Button dark={props.dark} desktop={props.desktop} type="button">
desktop? а это зачем?

2017-08-12 21:23 UTC, evgenyrodionov commented on src/Product/index.js
> +import IntroDesktop from './IntroDesktop';
используй react-responsive чтобы на мобайле не засорять версткой с десктопа (и наоборот)

2017-08-13 04:39 UTC, NoValentina commented on src/Product/Intro/Actions/index.js
> +    <Button dark={props.dark} desktop={props.desktop} type="button">
+

2017-08-13 04:42 UTC, NoValentina commented on src/Product/Desktop/Size/index.js
> +    <Buttons sizes={sizes} selectedSize="XL" />
+

2017-08-13 04:46 UTC, NoValentina commented on src/Product/Desktop/LinkHelp/index.js
> +const LinkHelp = () =>
+

2017-08-13 04:46 UTC, NoValentina commented on src/Product/Description/Text/index.js
> +  <div>
+

2017-08-13 04:47 UTC, NoValentina commented on src/Product/Description/Text/index.js
> +/*const Title = styled.h2`
+

2017-08-13 04:51 UTC, NoValentina commented on src/Header/index.js
> +    width: 221px;
+

2017-08-13 05:42 UTC, NoValentina commented on src/Product/index.js
> +import IntroDesktop from './IntroDesktop';
+

2017-08-13 05:43 UTC, NoValentina commented on src/Product/Description/index.js
> +const Photo2 = styled.img`
+

2017-08-13 11:55 UTC, imevro requested changes

2017-08-13 11:55 UTC, evgenyrodionov commented on src/Product/Description/index.js
> +            <Text description={description} />
передавай между тегами

2017-08-13 11:55 UTC, evgenyrodionov commented on src/Product/Intro/index.js
> +  height: 651px;
почему такой суперфикс, оставь только одну сторону

2017-08-13 11:55 UTC, evgenyrodionov commented on src/Product/Large/About/index.js
> +      <Actions primary small>
почему смолл?

2017-08-13 11:55 UTC, evgenyrodionov commented on src/Product/Large/About/index.js
> +      <Actions primary small>
смолл это кнопки выбора цены

2017-08-13 11:55 UTC, evgenyrodionov commented
Исправишь — напиши в телеграм

2017-08-13 12:30 UTC, NoValentina commented on src/Product/Description/index.js
> +            <Text description={description} />
+

2017-08-13 12:31 UTC, NoValentina commented on src/Product/Intro/index.js
> +  height: 651px;
+

2017-08-13 12:57 UTC, merged